-- CreateEnum
CREATE TYPE "DocumentSlot" AS ENUM ('APPLICATION', 'ID_PHOTO', 'SSN_CARD', 'CRIMINAL_HISTORY', 'FINGERPRINTS', 'INVESTIGATIVE_REPORT', 'SUITABILITY_REPORT', 'NOTICE_OF_RESULTS', 'NO_OBJECTION_LETTER', 'LICENSE_ISSUANCE', 'NIGC_RECEIPT');

-- AlterTable
ALTER TABLE "PersonDocument" ADD COLUMN     "slot" "DocumentSlot";
